### ISSUE TITLE
Front camera not performing scanning 

### ISSUE THREAD

**Issue by JacopoOrlandini** [microblink/blinkid-ios#378]
### Step 1: Are you in the right place?
  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

### Step 2: Describe your environment

  - Xcode version: Version 14.0 (14A309)
  - BlinkID SDK version: pod 'PPBlinkID', '~>5.20.0
  - What are you trying to scan: Front document with Front camera

### Step 3: Describe the problem

  - What happened? How can we make the problem occur and reproduce? This could be a description, log/console output, etc.
The problem consists in no scanning if front camera and correct scanning with back camera.
Test devices: iPad 7th gen and iPad 9th gen. For both device same behaviour.
The test document used is IT identity card always the same card, always the same light environment, nearly same distance.
Camera autofocus is enabled in iPad settings. 

### Step 4: Relevant code

```objective-c
    MBCameraSettings *cameraSettings = [[MBCameraSettings alloc] init];
    cameraSettings.cameraType = MBCameraTypeFront;
//    cameraSettings.cameraType = MBCameraTypeBack;

```

The same ViewController is used for performing scanning. For reproduce the issue I comment the TypeBack or TypeFront.
When TypeBack is enabled the scanning is fast and reliable
Instead when TypeFront is enabled Microblink SDK never performs the scanning on document.

Advice? Bug? Not enough front camera resolution?

**Comment by MBrizic01** [comment]
Hello @JacopoOrlandini 
I wanted to recap here what we discussed over the email so that it can serve as a reference to anyone interested in the topic. 
What you are experiencing is not related to a bug. It is a limitation of the front camera on the iPad.

The front camera on the iPad 7th and 9th Gen does not have autofocus, which is a big part of scanning the document since it can focus on a particular part, making SDK perform significantly better, as you can read [here](https://github.com/BlinkID/blinkid-ios#-requirements).
Also, the image quality is far better on the back camera on the iPad 7th gen (8 megapixels compared to the 1.2 megapixels on the front). 
We recommend using the back camera for all our clients since it has better image quality with autofocus.

I hope this information can be helpful to all our users, and we are closing the issue.

**Comment by JacopoOrlandini** [comment]
Leave a comment for future reference. 
### Camera Settings
The following snippet increases the success rate of decoding a document
``` objective-c
  MBCameraSettings *cameraSettings = [[MBCameraSettings alloc] init];
  --> cameraSettings.cameraType = MBCameraTypeFront;
  --> cameraSettings.cameraPreset = MBCameraPresetMax;
  MBBlinkIdOverlaySettings *settings = [[MBBlinkIdOverlaySettings alloc] init];
  settings.cameraSettings = cameraSettings;
  MBRecognizerCollection *recognizerCollections = [[MBRecognizerCollection alloc] initWithRecognizers:@[self.blickIdRecognizer]];
  MBBlinkIdOverlayViewController *blinkIdOverlayViewController = [[MBBlinkIdOverlayViewController alloc] initWithSettings:settings recognizerCollection:recognizerCollections delegate:self];

```
### Environment Condition
External variables that a developer cannot control but to keep in mind
* Good light environment => greater success rate 

Thanks for all the support

**Comment by MBrizic01** [comment]
@JacopoOrlandini Thank you for reporting here what we discussed over the mail. Happy to hear it helped you!
