### ISSUE TITLE
Incorrect checksum in SPM manifest

### ISSUE THREAD

**Issue by jakubdolejs** [microblink/blinkid-ios#399]
### Describe your environment

  - Xcode version: 14.3.1 (14E300c)
  - BlinkID SDK version: 6.2.0

### Describe the problem

After updating BlinkID from v6.1.2 using Swift Package Manager I get the following error in Xcode:

```
xcodebuild: error: Could not resolve package dependencies:
  checksum of downloaded artifact of binary target 'BlinkID' (50ccb0b3f1b980901683fd2042c2981bfaf379703a68a5aed9f773e43704a774) does not match checksum specified by the manifest (cd190bd437a9dd45435494ada51171d7cb01f3cca4497781e6aae0f54ecf0e88)
  fatalError
```

To reproduce this open Xcode, and in the project navigator select your project. Then, under the Package Dependencies click the + button to add a new package. In the search field and enter: https://github.com/BlinkID/blinkid-ios. Set Dependency Rule to "Up to next major version" and enter 6.2.0 in the version text field.

Then open Terminal in your project folder and enter the following command:
```
xcodebuild -resolvePackageDependencies
```

The error message suggests that the [checksum in the manifest file](https://github.com/BlinkID/blinkid-ios/blob/dc1fa0df5ddd2bac21f313cc0253243a2b58f429/Package.swift#L20) (Package.swift) is incorrect.

**Comment by MBrizic01** [comment]
Hello @jakubdolejs, thank you for reaching out. We made some changes, and in order to retrieve the latest framework, you should place the 'Dependency Rule' to 'Branch' and type in 'master', as shown in the attached image. 

[img](https://github.com/BlinkID/blinkid-ios/assets/99253784/3951c700-27e4-47f4-9649-3568f4f91035)

As we will not add a version tag for now, please use the master branch or a [specific commit](https://github.com/BlinkID/blinkid-ios/commits/master).

**Comment by jakubdolejs** [comment]
That worked. Thank you @MBrizic01
